# Use the official Node.js 20 image as a base
FROM node:20-alpine

# Set the working directory
WORKDIR /my-react-app

# Copy the rest of the application code
COPY . .

# Copy the package.json and package-lock.json
COPY .package*.json .

# Install dependencies
RUN npm install

# Verify vite installation in production mode
RUN npm list vite

# Build the application
RUN npm run build

# Expose the port that the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "preview"]